### ISSUE TITLE
[Mage][Talent] FoF + Frostbite

### ISSUE THREAD

**Issue by alycai** [playAnotherWay/Avalon#11]
Description:
when both fingers of frost and frostbite are fully spec'd into, both should proc at the same time.
Right now on avalon, you are able to proc a frostbite but not proc fingers of frost under certain circumstances.

How to reproduce bug:
spec 3/3 frostbite + 2/2 Fingers of frost, spam cast rank 1 frostbolt and observe the occasional frostbite proc with no accompanying FoF proc.

I do still observe fingers of frost procs which proc frostbite

How it should work:
Both should always proc at the same time

Screenshots:
https://imgur.com/d6ZnYjR

Relevant AddOns used:
N/A

External sources:
https://www.wowhead.com/forums&topic=132685/frostbite-and-fingers-of-frost
'' You have a single roll on a 20-sided die. If you have 15%/15%, then it's the same thing. If you get 18-20, they're frozen, and you get FoF. No second chance roll.''

https://web.archive.org/web/20090808144130/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_2_updated/
''Fingers of Frost
Fingers of Frost and Frostbite will always proc simultaneously if specced for both. This is intentional by design. The idea of the talent to make Frostbite useful in raids and some other situation where mobs/players do not stay frozen.''

https://wowwiki.fandom.com/wiki/Frostbite_(mage_talent)
''It will also always proc along with Fingers of Frost if both are fully talented. ''

Who are you?
Alycai

**Comment by alycai** [comment]
so I did some more testing just to further illustrate

I tested running 0/3 frostbite and 2/2 FoF with 100 rank1 frostbolt casts
then
I tested running 3/3 frostbite and 2/2 FoF with 106 rank1 frostbolt casts

this is what I found:

0/3 2/2 100 - 22 FoF
3/3 2/2 106 - 21 FoF + Frostbite -  15 Frostbite only

with no frostbite, 100 rank1 frostbolts procced FoF 22 times, with both frostbite and FoF fully talented, 106 rank1 frostbolts procced both FoF and frostbite 21 times, and procced frostbite 15 times with no FoF, I never observed a scenario with 3/3 + 2/2 where FoF procced without frostbite also proccing,

If I had to draw a conclusion from this, I would have to say that the 21 FoF + Frostbite is blizzlike, and the 15 frostbite only is wrong - but making those 15 frostbites proc FoF puts the total at 36, which sounds way over the supposed 15%/15%

**Comment by alycai** [comment]
More testing I've found that under some circumstances when you melee the mage you can proc a frostbite with no FoF proc:

https://imgur.com/uGWWpf7 - observe log and debuff for frostbite but no FoF proc on mage

**Comment by Marcelo1001** [comment]
The issue should be resolved, the fix was not pushed to the server before.

Best regards.
