### ISSUE TITLE
Mob "aggro range"

### ISSUE THREAD

**Issue by oxid95** [playAnotherWay/Avalon#122]
Description: Mobs aggro from way too far off. You can run on the road, and a mob from a fair distance from the road aggro. In crowded mob spawns its almost unfair how many come at you.

How to reproduce bug: Just go into casting distance of mobs (usually not supposed to be aggro range)

How it should work: Should be maybe half the distance it is now, if not less. 

Screenshots: 

Relevant AddOns used: 

External sources: Other people complain about it saying "its like this on other servers too"

Who are you?
Oxid, same in the discord.

**Comment by ghost** [comment]
https://wow.gamepedia.com/index.php?title=Aggro_radius&oldid=1977351#Formula
This is a past edit dated 6th August 2009. Later edits are from 2011 and beyond, so this is as close as it gets.

Things to especially note:
>The aggro radius of a mob having the same level as the player is roughly 20 yards (~ 18 meters)
Aggro radius varies with level difference at a rate of roughly 1 yard/level.
Minimum aggro radius for a mob seems to be combat range (5 yards).
Aggro radius is capped at a maximum of 45 yards, that is, when the mob is 25 or more levels higher than the player.
Vertical distance seems to be weighted much more heavily than horizontal distance. A mob standing on a ledge 4 yards above your head can fail to aggro even if standing 4 yards away from the same mob on level ground will draw aggro.

So, same-Level Mobs are supposed to have a 20yd Aggro Radius (f.ex. you're L30 around L30 Mobs). Each difference in Level adds/removes 1yd, down to a minimum of 5yd (15 Levels below, f.ex. you at L30 around L15 Mobs), up to a maximum of 45yd (25 Levels above, f.ex. you at L30 around L55 Mobs), but vertical Aggro Radius is much more forgiving at about 4yd standing above you failing to Aggro Mobs.

Question is, for the more technical, does this factor in Combat Reach, is it taken from the very epicenter of a creature's Hitbox (dead-center)? F.ex. would a creature with a big model and/or Hitbox and/or a long Combat Reach (f.i. Halion -- big model, big Combat Reach, as can be seen [here](https://www.youtube.com/watch?v=s5KLetVQn38&feature=youtu.be&t=143)) affect this? As per [this](https://www.youtube.com/watch?v=zFTceGrZIVk), it doesn't seem to be the case (Marrowgar is rather big model-wise, has a decent Combat Reach too) -- that shows a body-pull. See also [this](https://www.youtube.com/watch?v=CKUINzMQ_Fk&feature=youtu.be&t=279) -- no pull from the distance using the player's own PoV.

It's best to get [RangeDisplay](https://www.wowace.com/projects/range-display/files/445538), though GMs can use `.distance` -- you should be able to get an estimate of the distance at which Aggro happens (GMs' is more absolute at that).

Edit: Regarding Combat Reach, there's this (followed from [here](https://github.com/TrinityCore/TrinityCore/issues/17181)):
https://github.com/TrinityCore/TrinityCore/commit/980047763a685217e712f58b8713d48523d90ccb
> // The combatreach should not get taken into account for the distance so we drop it from the range (see Supremus as expample)

There also seems to be a line corresponding to Boss Aggro Radius:
> The aggro range of creatures with higher levels than the total player level for the expansion should get the maxlevel treatment
    // This makes sure that creatures such as bosses wont have a bigger aggro range than the rest of the npc's
    // The following code is used for blizzlike behaivior such as skippable bosses
    if (GetLevel() > expansionMaxLevel)
        aggroRadius = baseAggroDistance + float(expansionMaxLevel - player->GetLevel());

which may explain why Marrowgar can be body-pulled from relatively-close (see video again) considering he's a Raid Boss (Level 83), given that previously-given data would indicate he would've had +3yd added to his Aggro Radius on L80 Players.

**Update: After a while of playing, I can confirm that Aggro Range so far seems to be working as intended -- same-Level Mobs pull at ~20yd, scaled by 1yd for every Level in difference. _Haven't tested vertical Aggro Range as the quoted note describes yet (or I just haven't noticed anything out of the ordinary)._**
