### ISSUE TITLE
Autoattacking through pillars

### ISSUE THREAD

**Issue by Eltupi** [playAnotherWay/Avalon#139]
Description: Players can AutoAttack each other through pillars

How to reproduce bug: Stand around a pillar in AA range and attack. Spells (even meele spells) dont go through but AAs do. At the very end of the AA range both players need to move for this to be possible.

How it should work: You shouldnt be able to AA unless you are in line of sight. (we werent able to get a source to confirm this as a bug.)

Screenshots: check discord #general for a video.

Relevant AddOns used: None

External sources: None

Who are you? Eltupi (ingame / discord)

**Comment by ghost** [comment]
This is intended. Yes I know, it's dumb, but it's a thing.

What's even dumber is Taurens have a slightly-longer Combat Reach - - can hit from farther and be hit from farther. Imagine Tauren VS Tauren, with Leeway, and hitting through LoS using Auto Attack. It's ridiculous, but it is what it is.

https://m.youtube.com/watch?v=xjMRzrCOo2w
https://m.imgur.com/FDno7tU - - notice Travel Form doesn't count for it. See the icons and everything.
http://www.dual-boxing.com/archive/index.php/t-7338.html - - last handful of comments are dated during WotLK.
https://web.archive.org/web/20120115214911/http://www.arenajunkies.com/topic/19398-tauren-swing-range-all/
https://github.com/ccshiro/cc-buglist/issues/2494

But yeah, apart from the Tauren stuff, first video shows AA through LoS is intended. Taurens and Leeway only make it like you're Vergil from DMC doing Judgement Cuts all the way from Japan.

**Comment by Eltupi** [comment]
Yea I found simillar comments on the Warmane bugtracker but imho this still should be "fixxed" because its just to stupid. Old AT "fixxed" this aswell because the mechanic is just stupid. But they focused more on making the game competitive as on making the server 100% blizzlike.

**Comment by ghost** [comment]
"Fixing" it would mean making it not Blizz-like, because this was/is present on Retail.

By your argumentation, M2s not restricting LoS, Leeway as a whole, Spell Batching as a whole, and so many other features and mechanics, should be refuted as well. Might as well change the very game itself.

It's just Blizz and their (often odd) design choices and logic. It's the way the game was/is. You don't have to agree or disagree in regards to opinion.

**Comment by Eltupi** [comment]
Yes i know. 
Apparently tho ur "proof" video may be from another tbc pserver. We maybe can ask the video producer soon. Its just tbc but w/e.

**Comment by ghost** [comment]
It's not from a TBC private server.

The YouTube video is merely a more recent reupload.

[Here is the _original_ WCM link (deleted though).](https://www.warcraftmovies.com/movieview.php?id=82055&__cf_chl_jschl_tk__=4d5686e3013d80e3794ca05770c12b2c3d7649fc-1577820647-0-Ac4mJTA5nr1mTlIxbQJ_yG0hWTz8frlkRoamPWrzJYvEQaX5cqp2ciQ_TadnjAoiTDq5624Jr2KsAxg2k7vk4J4xpDyt63pZ_kog2MrnKrRVolkDdu4TIRP78uGFjnGBxVZpZaV7DeJRl1HxW7qFweQEHIw8P5CBa5jrS1x8vP-PvKA6SGceX9Q-_xNhfu-2_04heuvPh9v84MpCu8pr_h5efOY24QK6eEcmHz3JKObmX_jaU5yOiiwoRFpYZKgfZ57dFDFbUguFNTG4aMsh1i4feeRqyNeq0AiBatg734ib)
Date at the corner above to the right reads:
> 2008-07-12

Also, read comments. Load all of them and use Ctrl-F to search using terms like "pillar" and "los", etc.
> neverrrFame:4908-07-14 11:450 [+] [-] |  Too bad you can't even pillar kite tauren warriors.

> BenJmiinFame:5508-07-14 02:150 [+] [-] |  okay fix that and also fix the fcking tauren warriors hitting me true pillars

> spontanFame:3708-07-13 20:220 [+] [-] |  also good to note that the only thing either of those melee'ers can do is white swing from that range, and guess what it happens to all druids moving around pillars not just taurens

> spontanFame:3708-07-13 20:200 [+] [-] |  lets forget the part about how all taurens can hit people from longer ranges so a tauren target + a tauren aggressor can reach through a pillar and just assume that tauren druids are massive blocks that you can mortal strike from accross the map

> ReliunaFame:4408-07-12 23:180 [+] [-] |  Keep in mind that you can hit someone above the bridge in BEM arena when you are under it and that you are able to hit through pillar pretty easily.

> NearthfedFame:3908-07-12 20:510 [+] [-] |  laughed loud aufter seeing the warrior hitting you through these pillars

> DrenatheiFame:4408-07-12 19:010 [+] [-] |  "warriors aint crying over it :P and it got got some good sides aswell, for example taurens got easier time cycloning through pillars right?" It's only for melee THANKS FOR POSTING MOVIE ABOUT THIS!

> keorehFame:3208-07-12 16:370 [+] [-] |  my gnome lock also gets hitted through pillars, melee attacks should be melee, not ranged

> NylanderFame:4608-07-12 13:590 [+] [-] |  Yes please, tauren warriors can hit everyone through the pillars, not like that when it's a tauren hitting a tauren but still!

> XohFame:4708-07-12 12:390 [+] [-] |  Darkware, the reason you can be hitted through pillars is that you're fighting taurens who has 8 yard range on their melee attacks.

> IluxFame:5108-07-12 11:140 [+] [-] |  What ppl here say is true. Tauren warriors do have a larger hit-range. If ur doing arena the Tauren is the only race who can hit u from the bottom of while ur on the pillar (even in the middel of the pillar!). All he needs to do is to jump at the right time.

> TunesFame:6008-07-12 05:020 [+] [-] |  That really needs to be fixed, especially since you can be hit clear through pillars. I feel for you ms.tauren =[

> Justice411Fame:4108-07-12 04:450 [+] [-] |  u should make the other race cry when a tauren warrior can hit them through pillar, its so hard to kite a tauren warrior and u here complaining about ur hit box? reroll a warrior and u'll laugh

> SangradoFame:3808-07-12 00:490 [+] [-] |  Please fix, I hate getting mace stunned thru pillars by warriors T_T Also, why did you take that pic from Azgaz. I mean the movie pic in WCM.

**Edit: WotLK video source: https://youtu.be/OP63cb5cHf0?t=463 -- Orc Warrior swings at Klinda while clearly being behind the pillar.**
