### ISSUE TITLE
charge working in combat on warrior

### ISSUE THREAD

**Issue by Darreyy** [playAnotherWay/Avalon#16]
Description:
charge works in combat
How to reproduce bug:
nothing special needs to be done, it just shouldn't work in combat
How it should work:
work while not in combat
Screenshots:
don't think it's needed
Relevant AddOns used:
none
External sources:
none
Who are you?
Darreyy on both discord and ingame

**Comment by alycai** [comment]
are you sure you were not using the talent that allows for charge to be used in combat?

**Comment by Darreyy** [comment]
it's all good now, it was nothing^^
