### ISSUE TITLE
Core: Spamming "Refresh" on the Who List disconnects you

### ISSUE THREAD

**Issue by ghost** [playAnotherWay/Avalon#178]
Description:
Credit to @Eltupi.

Spamming the "Refresh" button while viewing the Who List disconnects you.

How to reproduce bug:
Open the Who List, spam "Refresh".

Just did this myself and I got disconnected every single time.

How it should work:
This shouldn't DC you.

Screenshots:
N/A

Relevant AddOns used:
N/A

External sources:
@Eltupi on the #general text channel under Avalon x9 WotLK category on Discord -- video example is there.

Who are you?
"Grayveil" in-game.

**Comment by MarceloTheOne** [comment]
We don't allow spamming any opcodes.

**Comment by Bellzubab** [comment]
Edited because it has been changed slightly.

Thank you!
