### ISSUE TITLE
Val'anyr, Hammer of Ancient Kings

### ISSUE THREAD

**Issue by Noodlerogue88** [playAnotherWay/Avalon#19]
Description:
It would appear that the mace's ability "Your healing spells have a chance to cause Blessing of Ancient Kings for 15 sec allowing your heals to shield the target absorbing damage equal to 15% of the amount healed." doesn't correctly proc when healing, and when i say correctly proc, it doesn't proc at all
How to reproduce bug:
Attempt to heal
How it should work:
it should "have a chance to cause Blessing of Ancient Kings for 15 sec allowing your heals to shield the target absorbing damage equal to 15% of the amount healed."

Deleted the other bullet points as they do not relate to the issue

Who are you?
Noodlerogue

**Comment by MarceloTheOne** [comment]
Can't reproduce, works correctly in combat.
