### ISSUE TITLE
Unable to use Medallion of the Horde on BG

### ISSUE THREAD

**Issue by Mirat23** [playAnotherWay/Avalon#214]
Description: 
I am a Horde player and whenever I am assign to the Alliance in BG, I am not able to use Medallion of the Horde. Please fix this bug that all players could use this trinket no matter of the fraction

How to reproduce bug:
NA

How it should work:
All players should be able to use Medallion during the BG battle

Screenshots:
NA

Relevant AddOns used:
NA

External sources:
NA

Who are you?
"Yamike" troll

**Comment by Eltupi** [comment]
A more generell take: You can't use/equip any faction specific items at all. You can't equip the Warsong Expidition rep shield for example if u are horde and play for alliance.

How to reproduce bug:
Queue BG and get in the opposing faction of the one you are (prob).
