### ISSUE TITLE
Weapon enchant cooldown

### ISSUE THREAD

**Issue by vedude** [playAnotherWay/Avalon#217]
Description:

Upon swapping weapons, enchants such as "Berserking" has a cooldown before proccing again. 

How to reproduce bug:

As soon as you swap to another weapon, or one-hand and a shield, the cooldown timer starts.

How it should work:

Enchants like "Berserking" and "Executioneer" is supposed to have no cooldown and able to refresh itself even if you swap weapons like on retail wotlk. This is extremely punishing for classes such as warrior that depend on changing weapons during PvP play.

External sources:

There was a forum post on blizzard forums that confirmed this, however due to the new forum layout, this topic is gone. However, I've reported this on other servers that has been solved.

Who are you?

Zypx, Human Warrior

**Comment by Psykopyro** [comment]
*nods*

**Comment by ghost** [comment]
I saw the original report you'd made on Sunwell long ago. Seems to be the same. Wonder if all the other issues in the later comments are also present here.

By the way you can use the Wayback Machine site to see if you can find snapped archives of old pages no longer conventionally accessible. Try that.

**Comment by vedude** [comment]
Yeah, but Sunwell solved this issue after a long time. Hoping they do the same :)
