### ISSUE TITLE
high dmg

### ISSUE THREAD

**Issue by Velene-hash** [playAnotherWay/Avalon#219]
Description:i found a normal npc (not elite) while trying to get to aliance ship in icecrown i think its doing too much dmg  for that kind of npc, it done 12853 frost dmg
Frostbrood Sentry
Spell:Bitter Blast

How to reproduce bug:

How it should work:

Screenshots:
![WoWScrnShot_010820_000117](https://user-images.githubusercontent.com/59645054/71967121-12cdf680-3203-11ea-9dc9-40af72fff3bc.jpg)

Relevant AddOns used:

External sources:

Who are you?

**Comment by ghost** [comment]
https://wotlk.evowow.com/?spell=60542

Intended.
