### ISSUE TITLE
Achievement Condition not triggering mount drop "A Tribute to Insanity (25 player)"

### ISSUE THREAD

**Issue by Noodlerogue88** [playAnotherWay/Avalon#26]
Description:
when killing anub HC with 50 attempts remaining a mount should drop, it doesnt.
How to reproduce bug:
Kill anub with 50 attempts remaining
How it should work:
on kill the extra loot after the boss should also contain a mount

Who are you?
Noodlerogue

**Comment by MarceloTheOne** [comment]
You get mount on mail after completing A Tribute To Immortality achievement, not insanity.

**Comment by Noodlerogue88** [comment]
I believe we are both incorrect, it comes from the 10m HM "A Tribute to Insanity", sorry for the mistake
