### ISSUE TITLE
Item enchant abuse.

### ISSUE THREAD

**Issue by ManiecAW** [playAnotherWay/Avalon#268]
Description: Noticed that a player might abuse an enchant added to his cloak from Engineering that normally shouldn't be allowed in Arenas or BG. The enchant i'm talking about is called "Flexweave Underlay". It allows you to fly up to 30yd away if you jump or and use the enchant mechanism at the same time. Same situation when used with Hunter's spell "Disengage".

How to reproduce bug: Go any Arena, enchant cloak with "Flexweave Underlay", try to jump/Disengage and use at the same time and see result.

How it should work: It should work as it's working but it shouldn't be allowed in Arenas/BG.

Screenshots: Couldn't catch it tho.

Relevant AddOns used: Not sure if any of them could be connected to the bug/mechanism.

External sources: I would like to avoid situations like in this video, not sure if it should be allowed in PvP such as Arenas/BG.

[LINK](https://www.youtube.com/watch?v=q2xbe0BLKIQ)

Who are you?

Maniec

**Comment by ghost** [comment]
Parachute from Flexweave Underlay/Springy Arachnoweave etc. are supposed to be usable. Same with Tinkers on Gloves (Hyperspeed Accelerators/Hand-Mounted Pyro Rocket). But Bombs (including Belt Tinkers) and Nitro Boosts (and similar) aren't usable in Arena.

All of that is usable in Battlegrounds though.

https://ptr.wowhead.com/forums&topic=121573

A trivial thing to note is that I believe in v4.0.3 (Cata), stuff like the Parachute from Flexweave was made not usable in Rated BGs and Arenas, but this is WotLK so it doesn't apply -- perhaps you got it confused with that initially?

**Comment by ManiecAW** [comment]
Thanks for you time and explanation.

As you said - this is WotLK so it doesn't apply ;) 

Cheers
