### ISSUE TITLE
Grobbulus "Poison Cloud"

### ISSUE THREAD

**Issue by Noodlerogue88** [playAnotherWay/Avalon#28]
Description:
Grobbulus will drop these below him every ~15 seconds. They will expand over time and last 75 seconds. They deal 4,250 Nature damage per second to anyone within.

This doesnt seem to be functioning correctly, i wish i could explain it more but when we tested we got 1 at the beginning and then they all spawned towards the end of the boss
How to reproduce bug:
Fight Grobbulus
How it should work:
Grobbulus will drop these below him every ~15 seconds. They will expand over time and last 75 seconds. They deal 4,250 Nature damage per second to anyone within.

Who are you?
Noodlerogue

**Comment by Noodlerogue88** [comment]
This was encountered on 10m difficulty

**Comment by MarceloTheOne** [comment]
Grobbulus script was rewritten, should be working fine now.
