### ISSUE TITLE
PvP/Wintergrasp/Core: No reduced Healing in Wintergrasp

### ISSUE THREAD

**Issue by ghost** [playAnotherWay/Avalon#286]
Description:
v3.3.2's change which reduces Healing in all BGs, Arenas, and Wintergrasp, is missing from Wintergrasp.

**Note that this should apply to BGs and Arenas _too_ -- if this is missing from them as well, then this should be implemented to all of them all the same.**

How to reproduce bug:
Go to Wintergrasp, do any sort of Healing (First Aid, Potion, Class Abilities, etc.), and compare to how much it _should_ be if it were reduced by 10%.

How it should work:
Healing should be reduced by 10% in all BGs, Arenas, and WG.

Screenshots:
N/A

Relevant AddOns used:
N/A

External sources:
https://wow.gamepedia.com/Patch_3.3.2#PvP
>- All healing abilities (including items such as potions) will be decreased in effectiveness by 10% when in Battlegrounds, Arenas, or Wintergrasp.

Who are you?
"Grayveil" in-game.

**Comment by MarceloTheOne** [comment]
Change will be implemented on appropriate progressive patch.

**Comment by ghost** [comment]
We're running 3.3.5a WoW WotLK -- with updated Spells all-around, making them stronger than they were back on original Retail content -- and you're telling me you're intentionally gonna let Healing be stronger than intended in PvP Zones?

Have you ever even PvP-ed, yourself? Do you _know_ what the difference is like here?
