### ISSUE TITLE
Grobbulus "Fallout Slime"

### ISSUE THREAD

**Issue by Noodlerogue88** [playAnotherWay/Avalon#29]
Description:
Grobbulus' spawned "Fallout Slime" freeze and refuse to move after being stunned once
How to reproduce bug:
Stun a Fallout slime
How it should work:
should revert back to normal movement behaviour after being stunned

Who are you?
Noodlerogue

**Comment by Noodlerogue88** [comment]
this was encountered on 10m difficulty

**Comment by Raydevv** [comment]
can confirm, happened whilst doing testrun with the Adopted Apes

**Comment by MarceloTheOne** [comment]
Grobbulus script was rewritten, should be working fine now.
