### ISSUE TITLE
Reflective Shield and Combat

### ISSUE THREAD

**Issue by Bellzubab** [playAnotherWay/Avalon#294]
Description: Reflective Shield puts you in combat. It should not.

How to reproduce bug: Have a priest specced into Reflective Shield PW:S himself. Duel him, put a DoT on him, and observe that you won't leave combat until after the DoT has faded +5.5 seconds (or whatever the combat timer is).

How it should work: Reflective Shield should not cause combat, and neither should similar effects (thorns, retribution aura, fire shield, molten armor).

Screenshots:

Relevant AddOns used:

External sources:

https://bitbucket.org/oregon/oregoncore/issues/619/bug-reflective-shield

http://www.warcraftmovies.com/movieview.php?id=129095

Around 10:05, he has rend and Power Word: Shield. You can see in his combat log that Reflective Shield hits the warrior (and the little smite-icon thingy on his scrolling combat text shows it). And he ends up leaving combat there (as he starts casting holy fire). It's kinda hard to see.

Who are you? Bellz

**Comment by ghost** [comment]
Correct -- note the combat icon on his UnitFrame fading right before he finishes the cast that got him back in Combat, as well as the MSBT announcements for leaving and entering Combat respectively.
