### ISSUE TITLE
Survival Instincts (Feral Druid) / Last Stand (Warrior)

### ISSUE THREAD

**Issue by Eltupi** [playAnotherWay/Avalon#298]
Description: If u cast Survival Instincts the extra HP you get is not added via addition but your new HP is just scaled percentual so for example if u have 50% hp and use survival Instincts u are still at 50% hp with 30% more max hp. If you use survival Instincts at ~5% hp u stay at ~5% hp and therefore heal like nothing from Survival Instinct.
Max HP: 20k   ------> 26k (survival instinct)
real HP: 1k --------> 1.3k

How to reproduce bug:
Use Survival Instincts

How it should work:
You should get the additional 30% HP added to your current health
Max HP: 20k   ------> 26k (survival instinct)
real HP: 1k --------> 7k

Screenshots:
Video on Discord #pvp by Eltupi

Relevant AddOns used: none

External sources: https://youtu.be/JYTqvFarc5o?t=343 you see the drood using Survival Instincts on low hp and he gets a bunch of HP

Who are you? Eltupi (Discord / Ingame)

EDIT: You don't lose the 30% HP at the end of Survival Instincts aswell it just gets scaled proportional again.

**Comment by ghost** [comment]
Might also want to have a check on Last Stand (Warrior Talent) as well.

This sounds like it might've been a backfire following the fix on the previously-incorrect HP scaling upon gaining and losing Commanding Shout.

**Comment by Eltupi** [comment]
Just checked and for Last Stand (Warrior) its exactly the same thing.

**Comment by ghost** [comment]
I wonder if these Spells are actually supposed to act the same way as Commanding Shout. I'm currently unavailable so I can't go scouring for sources on Last Stand/Survival Instincts when HP is low (f.ex. 10%) - - as in, does it increase Cur HP by the amount of Max HP said Spell adds (which was the original issue with Commanding Shout - - it was basically a makeshift-heal, which it wasn't supposed to be but is now working as intended).

If possible, post relevant sources until I can on my own as well.

**Comment by Eltupi** [comment]
Look at the video I edited in the original post the quality is quite low but its from Retail back then and you see the Drood getting a huge amount of life after using Survival Instincts on low HP

**Comment by ghost** [comment]
Saw the edit but the video I'll check once I'm back - - 's friggin' impossible on the phone at that quality.

**Comment by Eltupi** [comment]
https://wowwiki.fandom.com/wiki/Survival_Instincts_(druid_ability)
Patch 3.0.8 (2009-01-20): Now temporarily grants you 30% of your current maximum health for 20 sec. (Old - 30% of your maximum health). The extra health from this ability now persists in all forms, but the ability can only be activated in Cat Form, Bear Form, or Dire Bear Form. This prevents the health gain from occurring multiple times if constantly shapeshifting.

https://wowwiki.fandom.com/wiki/Last_Stand
Last Stand is a warrior ability learned at level 38 for those with the Protection specialization. It is a short duration self-buff that temporarily adds 30% of the Warrior's maximum health for 15 seconds. At the end of this time, this health is removed.

**Comment by ghost** [comment]
Back now, so went to see properly now, did some of my own searching too. Sources are valid -- good show.

Checked your video added in the edit and yeah, the HP jump corresponds to the Max HP gain from Survival Instincts. Traced the original video to WCM and it was uploaded on 15th Jan 2009 ([here](https://www.warcraftmovies.com/movieview.php?id=99055)). Patchnote is correct.

Furthermore, found this:
https://youtu.be/pUiDsNpIh3c?t=103
which is uploaded May 20th 2009. Note the HP jump -- same as with Survival Instincts seen above.

Confirmed -- Last Stand/Survival Instincts behave differently from Commanding Shout/Blood Pact -- the former two are supposed to add the Max HP to Current HP as well, unlike the latter two. Currently this bug makes Ferals and Warriors with SI/LS respectively gamebreakingly-nerfed in an unintended way in both PvE and PvP, making them literally wasteful if used when low on HP.

Should edit report title to add Last Stand (Warrior) as well, by the way.
