### ISSUE TITLE
Malygos Bug

### ISSUE THREAD

**Issue by Noodlerogue88** [playAnotherWay/Avalon#31]
Description:
Malygos instantly lands instead of having its RP fly down, briefly seen in video listed below
How to reproduce bug:
Trigger Malygos
How it should work:
after activating the encounter, she should RP fly and land before the encounter begins
Screenshots:
https://youtu.be/HvPvWIEiUsk?t=16
Who are you?
Noodlerogue

**Comment by MarceloTheOne** [comment]
Can't reproduce, works correctly.
