### ISSUE TITLE
Cant use Savory deviate delight in treeform

### ISSUE THREAD

**Issue by marcinb12500** [playAnotherWay/Avalon#316]
Description: It wont overwrite treeform, like it does in all servers I have polayed

How to reproduce bug: Just click the fish

How it should work: should overwrite tree form

Screenshots: 

Relevant AddOns used:

External sources:

Who are you? I am EMO alliance

**Comment by ghost** [comment]
https://wow.gamepedia.com/index.php?title=Savory_Deviate_Delight&oldid=2480653
>Druids, Shamans, and Warlocks lose the effect when they change forms.

Intended behavior.
