### ISSUE TITLE
thistle tea

### ISSUE THREAD

**Issue by CryWolff** [playAnotherWay/Avalon#32]
Description:
thistle tea potion add 330 energy instead of 100
How to reproduce bug:
check the item in bag
How it should work:
should add 100 energy 
Screenshots:

Relevant AddOns used:

External sources:
https://wotlk-twinhead.twinstar.cz/?item=7676
Who are you?

**Comment by MarceloTheOne** [comment]
Thistle Tea should not give 100 energy, at least not in all cases, the proper formula is shown here: https://wowwiki.fandom.com/wiki/Thistle_Tea ([100 - (2 * (Player Level - 40))]).
