### ISSUE TITLE
Survival Instincts (druid feral talent)

### ISSUE THREAD

**Issue by greedman456** [playAnotherWay/Avalon#324]
Description:
Survival instincts is only adding to your max health and giving you %of your current health as bonus

How to reproduce bug:
Pick the talent Survival instincts and use it.

How it should work:
30% of your maximum health should be added to your current health and your maximum health cap should be increased by the same amount.

Screenshots:
-
Relevant AddOns used:
-
External sources:
https://www.wowhead.com/spell=61336/survival-instincts#comments
Quoting from patch 3.0.3

By Drenvion (4,725 – 10·57) on 2008/12/18 (Patch 3.0.3) 
You will never be killed by expiering abilities or items that increases your maximum health.
Upon expiration it will remove your 30% health increase regardless of how much that is at the time when it expires, should you have less than 30%health you will be reduced to 1%hp.
This will also heals you for 30% health, for example if you use this while having 20%health you will end up having 50%.
In PvE this is amazing, in PvP it's good for what it does, but it's neglective effect is that should you drop below 30% while this is active you have no chance of surviving when those 20seconds is over unless you are in bear and have Frenzied Regeneration ready. - This is if you don't have a healer with you, something you will have in PvE.
It should be used with caution and preferably used before you are near low hp in PvP, in PvE it is used to save yourself from dieing - Just make sure your healer(s) know you have used it.
Check Last Stand for more information as Survival Instincts is a direct(other than the Cat/Bearform requirement and name) copy of that ability.

Who are you?
Greedman account name, gorthan druid in-game

**Comment by ghost** [comment]
It's already been reported.

#298 resolved but not implemented just yet. Wait until then.
