### ISSUE TITLE
DK/unholy/talent Improved unholy presence 2/2

### ISSUE THREAD

**Issue by zole1988** [playAnotherWay/Avalon#325]
Description: 

How to reproduce bug: Take improved UH presenc,be in UH presence and take addon to track rune CD

How it should work: Runes should start CD with 9 sec

Screenshots:Description: https://files.fm/u/ek6qhfee

Relevant AddOns used:

External sources:

Who are you? Deadlyzole

**Comment by Aridam** [comment]
https://db.omegawow.eu/?search=improved+unholy+presence for reference.
While in Unholy Presence, R1 of this Talent -- 5% -- would mean 9.5s, while R2 -- 10% -- would mean 9s, so yes.
>and your runes finish their cooldowns 5% faster in Unholy Presence.

>and your runes finish their cooldowns 10% faster in Unholy Presence.

**Comment by Bellzubab** [comment]
Maybe there's something wrong with your timers?

1/15 15:47:20.206  SPELL_CAST_SUCCESS,0x0000000000001EF2,"CharNameOmitted",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20
1/15 15:47:20.400  SPELL_CAST_FAILED,0x0000000000001EF2,"CharNameOmitted",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20,"Not yet recovered"
1/15 15:47:21.297  SPELL_CAST_SUCCESS,0x0000000000001EF2,"CharNameOmitted",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20
1/15 15:47:21.405  SPELL_CAST_FAILED,0x0000000000001EF2,"CharNameOmitted",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20,"Not yet recovered"
1/15 15:47:27.113  SPELL_CAST_FAILED,0x0000000000001EF2,"CharNameOmitted",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20,"Not yet recovered"
1/15 15:47:29.430  SPELL_CAST_SUCCESS,0x0000000000001EF2,"CharNameOmitted",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20

My DK has 0 haste. I am in UH presence with the improved UH presence talent. I Blood Boil twice to put both my blood runes on CD. I then spam Blood Boil until it goes off.

15:47:29.430  - 15:47:20.206 = 9.224 seconds between my blood rune going on CD, and off CD, which can pretty much line up with server update time/my ping/not spamming the button hard enough.

**Comment by zole1988** [comment]
When runes are on CD they have lower CD with and without improved UH presence.Poin is thet with and without improved UH presence u have same cds

**Comment by zole1988** [comment]
I played with that addons and timers 8 years ago or even more till now and i know what im talking.Runes have system to lower CDs when they are already used but that is not connected with improved UH presence

**Comment by Bellzubab** [comment]
1/15 16:09:34.144  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49222,"Bone Shield",0x8
1/15 16:09:34.144  SPELL_AURA_REFRESH,0x0000000000001EF2,"~~~",0x511,0x0000000000001EF2,"Infuriated",0x511,49222,"Bone Shield",0x8,BUFF
1/15 16:09:40.019  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,48263,"Frost Presence",0x10
1/15 16:09:40.019  SPELL_AURA_REMOVED,0x0000000000001EF2,"~~~",0x511,0x0000000000001EF2,"Infuriated",0x511,48265,"Unholy Presence",0x20,BUFF
1/15 16:09:40.019  SPELL_AURA_APPLIED,0x0000000000001EF2,"~~~",0x511,0x0000000000001EF2,"Infuriated",0x511,48263,"Frost Presence",0x10,BUFF
1/15 16:09:42.908  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20
1/15 16:09:42.947  SPELL_CAST_FAILED,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20,"Not yet recovered"
1/15 16:09:44.426  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20
1/15 16:09:44.510  SPELL_CAST_FAILED,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20,"Not yet recovered"
1/15 16:09:53.170  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20

16:09:53.170 - 16:09:42.908 = 10.262

9.224 seconds with UH presence + imp UH presence, 10.262 in frost presence

It's working properly.

**Comment by Bellzubab** [comment]
1/15 16:09:34.144  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49222,"Bone Shield",0x8
1/15 16:09:34.144  SPELL_AURA_REFRESH,0x0000000000001EF2,"~~~",0x511,0x0000000000001EF2,"~~~",0x511,49222,"Bone Shield",0x8,BUFF
1/15 16:09:40.019  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,48263,"Frost Presence",0x10
1/15 16:09:40.019  SPELL_AURA_REMOVED,0x0000000000001EF2,"~~~",0x511,0x0000000000001EF2,"~~~",0x511,48265,"Unholy Presence",0x20,BUFF
1/15 16:09:40.019  SPELL_AURA_APPLIED,0x0000000000001EF2,"~~~",0x511,0x0000000000001EF2,"~~~",0x511,48263,"Frost Presence",0x10,BUFF
1/15 16:09:42.908  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20
1/15 16:09:42.947  SPELL_CAST_FAILED,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20,"Not yet recovered"
1/15 16:09:44.426  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20
1/15 16:09:44.510  SPELL_CAST_FAILED,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20,"Not yet recovered"
1/15 16:09:53.170  SPELL_CAST_SUCCESS,0x0000000000001EF2,"~~~",0x511,0x0000000000000000,nil,0x80000000,49941,"Blood Boil",0x20

16:09:53.170 - 16:09:42.908 = 10.262 seconds without UH pres + imp UH pres, 9.224 seconds with both. Seems fine to me.

**Comment by zole1988** [comment]
To be honest i dont understand that picture with codes but i know how it was on retail and also working on arena tournament.CDs are lower

**Comment by zole1988** [comment]
I dont know if they fixed it but now its working like it should, starting from 9 sec but when blood rune became death rune, death rune starting from 10 sec.
