### ISSUE TITLE
WG leave button

### ISSUE THREAD

**Issue by zole1988** [playAnotherWay/Avalon#326]
Description:When i use icon to leave WG i get CD on heart stone

How to reproduce bug:Use WG icon to leave ans look at heart stone

How it should work:Teleport u in dalaran without using your CD on heart stone

Screenshots:

Relevant AddOns used:

External sources:

Who are you?

**Comment by Bellzubab** [comment]
Double of #288

**Comment by ghost** [comment]
#262 #288 
Check sources there -- it's supposed to do it.
It's also supposed to teleport you to your HS location even if it's on CD.
It's one of those old so-called "ghetto-hearth" methods available back then on Retail.

Edit: Goddammit Bellz.
