### ISSUE TITLE
Sapphiron Bug

### ISSUE THREAD

**Issue by Noodlerogue88** [playAnotherWay/Avalon#33]
Description:
After Sapphiron does her ice tomb ability, she is to land and NOT drop her threat, however currently after landing she drops all threat from her threat table
How to reproduce bug:
Allow Sapphiron to fly up, then land, upon landing the issue happens
How it should work:
Currently trying to find "Proof" so you can enforce the changes, but there is not mean't to be a threat wipe. 
Screenshots:
25m http://prntscr.com/qa1ydv
10m http://prntscr.com/qa1yh1
(Source) https://wowwiki.fandom.com/wiki/Sapphiron_(tactics)
Who are you?
Noodlerogue

Hopefully video footage from retail for proof to come

**Comment by Noodlerogue88** [comment]
https://youtu.be/d4_7KnZqyjc?t=70 Historical Footage of a Sapphiron fight (10m) with a threat meter displayed, as you can see during the whole flight phase there is not a single aggro dump

**Comment by MarceloTheOne** [comment]
Can't reproduce, there is no threat reset already.
