### ISSUE TITLE
Improved Scorch

### ISSUE THREAD

**Issue by parahawk** [playAnotherWay/Avalon#34]
Description: Scorch not applying debuff

How to reproduce bug: Cast scorch with improved scorch 3/3 talent taken and the scorch debuff (5% increase to critically hit) isn't appearing on the target

How it should work: Should apply 5% increased change to critically hit on target when scorch is used

Screenshots:

Relevant AddOns used:

External sources:

Who are you? Parahawk

**Comment by Noodlerogue88** [comment]
I can't seem to replicate this bug, attempted on a level 80 (boosted) Blood Elf mage with talent spec below.

Please include more information to narrow down the bug search

http://prntscr.com/qa2ft5

**Comment by Noodlerogue88** [comment]
After a short discussion with Parahawk in game it would seem that a restart of client remedied this bug.

**Comment by MarceloTheOne** [comment]
Can't reproduce.
