### ISSUE TITLE
Slow Fall Glyph

### ISSUE THREAD

**Issue by parahawk** [playAnotherWay/Avalon#35]
Description: Slow Fall Glyph should allow slow fall to be used without a reagent 

How to reproduce bug: Take glyph of slow fall and then use slowfall and the message missing reagent light feather appears 

How it should work: With glyph no reagent should be required

Screenshots:

Relevant AddOns used:

External sources:

Who are you? Parahawk Discord

**Comment by Noodlerogue88** [comment]
I can't seem to replicate this bug, attempted on a level 80 (boosted) Blood Elf mage.

Glyph was applied then straight after slow fall was applied without a reagent.

**Comment by Noodlerogue88** [comment]
After a short discussion with Parahawk in game it would seem that a restart of client remedied this bug.

**Comment by MarceloTheOne** [comment]
Can't reproduce.
