### ISSUE TITLE
Glitch under stormwind

### ISSUE THREAD

**Issue by parahawk** [playAnotherWay/Avalon#36]
Description: The glitch to get under stormwind work

How to reproduce bug: see youtube vid https://www.youtube.com/watch?v=5q_FPMk3Eg8

How it should work: wall shouldn't allow character to drop through. on live blizz server this did work but you can travel long distances under stormwind without interruption and horde able to use to hide under stormwind

Screenshots: https://drive.google.com/file/d/1yKghxe-qhGlJ6nMjCt_hsi-IXvn6LiAw/view?usp=sharing

Relevant AddOns used:

External sources:

Who are you? Parahawk Discord

**Comment by Noodlerogue88** [comment]
WotLK Patch 3.3 was released on December 9th 2009, your video evidence on how to reproduce the bug was uploaded on November 29th 2009 so it is assumed that it was from the 3.2 patch of WotLK, making this "Bug" as intended for the wow expansion we are playing on.
