### ISSUE TITLE
Quest: Flown the Coop!

### ISSUE THREAD

**Issue by Fixetza** [playAnotherWay/Avalon#39]
Description: In the quest "Flown the Coop!" players are supposed to capture 12 chickens that start running fast around Frenzyheart hill. The thing is that the chickens just stand around and don't even run so you can capture them really fast.

How to reproduce bug: Take the quest "Flown the Coop!" from Frenzyheart hill and observe the chickens.

How it should work: Chickens should run around and somewhat fast at that.

Screenshots:

Relevant AddOns used:

External sources: 

Who are you? Discord: Darer

**Comment by Noodlerogue88** [comment]
https://www.youtube.com/watch?v=NgqmDixapJE Footage from 2013 backing up what Fixetza/darer is saying
