### ISSUE TITLE
Mechanics/Formula : Heirloom Rates

### ISSUE THREAD

**Issue by kutaycoskuner** [playAnotherWay/Avalon#393]
Description:
Tattered Dreadmist Robe heirloom normally providing a 10% experience bonus but It is increasing so much more for 180k experience giving quest I am earning 250k experience.

How to reproduce the bug:
Wear Tattered Dreadmist Robe and check experience levels by completing quests

How it should work:
It should increase experience gain bonus by 10%

Screenshots:
Before
<img width="450" height="258" src="https://cdn.discordapp.com/attachments/352191074581741570/668512375418126336/WoWScrnShot_011920_204809.jpg">

After
<img width="450" height="258" src="https://cdn.discordapp.com/attachments/352191074581741570/668512382082875392/WoWScrnShot_011920_204815.jpg">

Relevant AddOns used:
None

External sources:
None

Who are you?
Ingame: Orthrin, Gilda
Discord: Orthrin#6056

**Comment by Bellzubab** [comment]
You are Alliance. Alliance players currently get a +30% boost to experience gained. This is not reflected in the quest tooltip.

That Call to Arms quest gives 20.1k normally. The server rate is 9x, so it shows 180.9k.

So you have 9x from the server rate, an extra 30% xp from being Alliance, and 10% from the heirloom.

9 * 1.3 * 1.1 = 12.87x default XP.

12.87 * 20100 = 258687, the exact amount of experience you gained.

**Comment by ghost** [comment]
Bellz's right on the money here.

**Comment by kutaycoskuner** [comment]
I totally forgot about the 30% thanks!
