### ISSUE TITLE
Mobs not moving when pulled, also when DoT is applied it gets nullified

### ISSUE THREAD

**Issue by Raydevv** [playAnotherWay/Avalon#40]
Description:
When some mobs are pulled in starting areas sometimes they won't move when aggro'd by a ranged ability

How to reproduce bug:
Attack a mob with range, pray on RNG it doesn't move

How it should work:
They should move & slap you to death

Screenshots:
https://cdn.discordapp.com/attachments/642527259374125124/655374770547982356/unknown.png
https://cdn.discordapp.com/attachments/642527259374125124/655376931264528394/unknown.png
https://cdn.discordapp.com/attachments/642527259374125124/655376964588273664/unknown.png

no ss of the dot being nullified though

Relevant AddOns used:
-
External sources:
-
Who are you?
Raydev

**Comment by MarceloTheOne** [comment]
Can't reproduce, could you tell me what ability caused it?

**Comment by Raydevv** [comment]
Happend with rank 1 fireball as mage for me
