### ISSUE TITLE
Charge/Intervene/Intercept Interpolation after update

### ISSUE THREAD

**Issue by Bellzubab** [playAnotherWay/Avalon#408]
Description: Since the update this morning ( #401 ), Charge Interpolation is TOO good. It should only work for about a couple yards. You shouldn't pingpong around if someone's mounted, and you shouldn't be able to make it pretty much all the way around a pillar from someone being in your LoS for milliseconds.

How to reproduce bug: https://www.youtube.com/watch?v=nRuud7NCHac

How it should work: I don't think he should even be able to get that charge at all, but call it a ping thing. He should definitely end up a lot closer to the left side of the pillar, not in my exact center. And he definitely shouldn't turn into The Flash when he rounds that corner of the pillar.

Screenshots:

Relevant AddOns used:

External sources: I'm not sure I can find a source for an edge case like this. I think it's fairly intuitive that it isn't supposed to work *like this*

Who are you? Bellz

**Comment by ghost** [comment]
Yeah that looks like it shouldn't work -- looks like it's able to sometimes predict a bit farther than it should. It's capable of undershooting and overshooting by default, but this is a bit _too_ much. That zappy corner turn also looks outright unnatural.

Judging by when things occurred by going through this frame-by-frame, it's possible it was a ping issue (he literally cast it when you were already behind the pillar), but that reach was abnormal, not to mention ending up literally INSIDE of your Hitbox -- almost dead-center.

For the record, sometimes interpolation still backfires and doesn't do a whole lot, but that's Blizz-like (it still kinda sucked on Retail WotLK), but it's never supposed to be _this good_ either.

Examples:
https://youtu.be/1IAasBdk68Y?t=121 -- this one sucked the fat one.
https://www.youtube.com/watch?v=1IAasBdk68Y&feature=youtu.be&t=317 -- this one was good but the guy slid past anyway.
https://www.youtube.com/watch?v=3cGqlcE44m0&feature=youtu.be&t=117 -- this is pretty much among the best.

The whole of Veev, Klinda 6-8, Hoodrych 4 & 5, and Boocraft's "Kill Them All" and [his other video](https://www.youtube.com/watch?v=7sZH6V5sl50) have examples of great, bad, and average Charge interpolation examples scattered about.

Add the original sources as per #401 as well.
