### ISSUE TITLE
mobs in Hibernal Cavern not moving towards player

### ISSUE THREAD

**Issue by Crzyfist** [playAnotherWay/Avalon#43]
Description: Some mobs in Hibernal Cavern (Sons of Hodir quests) are not moving to player after being attacked. Ravenous Jomungar + Icemaw Bear

How to reproduce bug: get aggro from them or attack them with a spell

How it should work: they should move to the player and attack him

Screenshots: https://imgur.com/JpLt3cS   as seen it is attacked and did not move towards me 
2nd screen a few min later: https://imgur.com/4YuHUUc
Relevant AddOns used: shouldn't be any relevant one, using bartender, shadowed unit frames, dbm, skada and some more

External sources: gameplay on retail/other servers

Who are you? Crzy in discord

**Comment by MarceloTheOne** [comment]
https://github.com/playAnotherWay/Avalon/issues/40
