### ISSUE TITLE
[INVALID] (Part 2) Death Knight/Spell: Frost Strike - cannot be Dodged or Parried

### ISSUE THREAD

**Issue by ghost** [playAnotherWay/Avalon#446]
Description:
#405 is incomplete -- Frost Strike can be Blocked but it cannot be Dodged or Parried.

Please fix this else we're just gonna see Frost Death Knights dominating PvE and _especially_ PvP.

I just get wrecked in PvP save for using Shield Block -- other than that, my Parry (+Deflection Talent) and Dodge Stats are useless VS them.

How to reproduce bug:
Fight against a Frost DK, have them spam Frost Strike -- note no Dodges or Parries, only ever Blocks (if using a Shield).

How it should work:
Frost Strike should be capable of being Dodged and Parried as well just as it can be Blocked.

Screenshots:
N/A

Relevant AddOns used:
N/A

External sources:
#405 
https://wow.gamepedia.com/Frost_Strike
> # Patch 3.2.0 (2009-08-04): This ability can now be _dodged, parried, or blocked_. Weapon damage bonus reduced to 55%, down from 60%.

Who are you?
"Grayveil" in-game.

**Comment by Bellzubab** [comment]
It could be dodged/parried prior to the update.

**Comment by Bellzubab** [comment]
This is working fine. Just dueled a rogue on my FDK, and he was dodging Frost Strike during evasion.

Perhaps you didn't test this extensively enough?

**Comment by ghost** [comment]
Had two prolonged fights VS the same FDK as stated and could only Block (using Shield Block). I doubt I'm _that_ unlucky.

Try without Evasion, have the DK use weaker Weapons so that the Damage won't be an issue for test downtime.

**Comment by Bellzubab** [comment]
Dueled my feral, could dodge it.

Dueled my ret, could dodge and parry it.

**Comment by ghost** [comment]
>21:26:50> Forsakenxn's attack was parried by Grayveil. 
21:26:50> Forsakenxn's attack was blocked by Grayveil.(329 Blocked) 
21:26:50> Forsakenxn casts [Mind Freeze] at Grayveil. 
21:26:50> Forsakenxn [Mind Freeze] was reflected by Grayveil. 
21:26:50> Forsakenxn casts [Frost Strike] at Grayveil. 
21:26:50> Forsakenxn's [Frost Strike] was dodged by Grayveil.

I'm fuckin' unlucky it seems.
Now I'm striking gold.
