### ISSUE TITLE
Furry warrior talent Bloodthirst broken?

### ISSUE THREAD

**Issue by hatelock** [playAnotherWay/Avalon#456]
Description:  Bloodthirst ability says that instantly deal 2173 dmg and its based on attack power...
With 4.5 k AP i cant make more than 1500- 1800 + dmg with it on normal strikes.. 
somehow no sense at all ? 

How to reproduce bug:

How it should work: 

Screenshots:

Relevant AddOns used:

External sources:

Who are you? Armstrong in game

**Comment by ghost** [comment]
Did you factor in Armor? It's Physical Damage.
The Damage in the Tooltip is the actual Damage with the Attack Power you have at the time of viewing -- it being 2173 doesn't mean having more AP will actually add a hidden extra value; 2173 means 2173 with all that AP accounted for. Acquire more or lose some AP and view Tooltip again -- you'll see the value changes, so it reflects that amount.
https://db.omegawow.eu/?spell=23881
