### ISSUE TITLE
Iron Council -- Ulduar PTR

### ISSUE THREAD

**Issue by Raydevv** [playAnotherWay/Avalon#458]
Description:
Runemaster Molgeim his ability Shield of Runes is not able to be dispelled and/or spellstolen.

How to reproduce bug:
Encounter fight, wait for shield, try to dispell/spellsteal

How it should work:
"Shield of Runes - Shield absorbs up to 50,000 heroic 20,000 normal damage. If the shield absorbs the total amount this gives Moldeim a 50% damage increase for 15 seconds. Should be purged, dispelled or spellstolen." -- https://wowwiki.fandom.com/wiki/Assembly_of_Iron
Screenshots:
-
Relevant AddOns used:
-
External sources:
-
Who are you?
Raydev

**Comment by Raydevv** [comment]
Possible relevant note: this was on 10 man difficulty. After speaking to other people doing 25m they were able to do it

**Comment by ghost** [comment]
What do you mean "can't reproduce"? We couldn't Dispel/Spellsteal using _anything_ -- me personally, I did Shield Slam and no matter when, I could _not_ Dispel it; _nobody_ could.

Might wanna reinvestigate.

**Comment by Raydevv** [comment]
+1 still bugged

**Comment by micahmones** [comment]
seems only broken on 10m, we're able to spellsteal on 25m just wanted to add (not sure if your above comment referred to our team)
- wade
