### ISSUE TITLE
Ulduar 10 - Thorim: Thorim's Stormhammer targeting players in gauntlet

### ISSUE THREAD

**Issue by micahmones** [playAnotherWay/Avalon#469]
Description: Thorim's Stormhammer targets and hits players that are in the gauntlet

How to reproduce bug: Unknown, but it happened twice in about 5 pulls

How it should work: Thorim's Stormhammer ability should only be hitting players in the arena

Screenshots: https://clips.twitch.tv/HilariousAstuteEagleVoteYea
Thorim's Hammer hits paladin named "Fix"

Relevant AddOns used: N/A

External sources: N/A

Who are you?
Wade

**Comment by Raydevv** [comment]
This happened in 25m yesterday.

**Comment by micahmones** [comment]
@MarceloTheOne still broken and targeting players in gauntlet in 25m
