### ISSUE TITLE
Wailing Caverns, unable to finish.

### ISSUE THREAD

**Issue by Psykopyro** [playAnotherWay/Avalon#48]
Description: Wailing Caverns last boss, unable to access due to beginning NPC not offering escort.

How to reproduce bug: Complete all bosses in Wailing Caverns except the last boss. Go to NPC, they do not offer the escort portion of the dungeon to summon the last boss.

How it should work: NPC at beginning of dungeon should offer escort to last boss after all other bosses are dead.

Screenshots: N/A

Relevant AddOns used: N/A

External sources: N/A

Who are you? Psykopyheal, alliance priest.

**Comment by Noodlerogue88** [comment]
Completed earlier with a random group, working as intended
