### ISSUE TITLE
Darkmoon Card: Berserker! proc

### ISSUE THREAD

**Issue by CraftedRO** [playAnotherWay/Avalon#499]
Description: 
Darkmoon Card: Berserker! proc on priests even if you are out of combat from self renew .
Is possible to proc from other classes self-heals too .

How to reproduce bug: 
On a priest , self-cast renew spell even out of combat.

How it should work:

> "Equip: You have a chance to gain Berserker when you deal or take damage in combat, increasing your critical strike rating by 35 for 12 sec. Effect stacks up to 3 times."

Screenshots: N / A

Relevant AddOns used: N / A

External sources: N / A

Who are you? Crafted

**Comment by Aridam** [comment]
Source to add: https://www.wowhead.com/forums&topic=150341 -- from when it got changed; should only be DMG done or DMG taken.
Additionally, proc chance of Spell: https://wotlk.evowow.com/?spell=57351 -- 50%.
Confirmed -- non-damaging actions should _not_ proc Berserker.
