### ISSUE TITLE
Reload UI and missing Hunter Pet control bar

### ISSUE THREAD

**Issue by Hygnxx** [playAnotherWay/Avalon#526]
Description: If you /reload ui with a hunter pet active the pet bar will dissapear and you will not able to use the /petattack command.

How to reproduce bug: Summon a hunter pet and /reload ui

How it should work: The pet control bar should reload with the UI

Screenshots: ![WoWScrnShot_020420_101957](https://user-images.githubusercontent.com/60664006/73769626-3a4bac80-4738-11ea-8837-952f0546a5c5.jpg)

Relevant AddOns used:

External sources:

Who are you? User Hygnx -- in game character 'Zelph' [A] Hunter

**Comment by Aridam** [comment]
Pet Action Bar and Pet control commands should persist even through `/rl / /reload / /reloadui / etc.` -- confirmed as a bug.

**Comment by micahmones** [comment]
happens with warlocks too
