### ISSUE TITLE
Death Knight/Spell/NPC

### ISSUE THREAD

**Issue by emilmez** [playAnotherWay/Avalon#532]
Description: Ebon Gargoyle [https://wotlk.evowow.com/?npc=27829](url) summoned by [https://wotlk.evowow.com/?spell=49206](url) does not get affected from any Buffs/Auras (like totems, paladin auras, antimagic zone, horn of winter etc). Only targeted buffs work on it.
As you can see in the video , the ghoul benefits from my 3 buffs, while the gargoyle doesn't.

How to reproduce bug:
Summon your gargoyle , try to give to it any kind of aoe buff / aura.

How it should work:
Ebon Gargoyle should benefit from buffs/auras the same way the Ghoul pet does.

Screenshots: [https://www.youtube.com/watch?v=emNt9OpbSFs](url)

Relevant AddOns used:

External sources:

Who are you?
Emil

**Comment by seadix** [comment]
No it shouldnt get those buffs it just scales (haste/AP/dmg %) of the player. Tried on sunwell/blackrock pvp. [https://imgur.com/a/WvNqA3l](url)

or this one which says almost the same that its bugged by gaining spellpower and raid buffs
[https://www.warmane.com/bugtracker/report/66919](url)
