### ISSUE TITLE
Dual Wield Specialization and spell hit

### ISSUE THREAD

**Issue by Azraelft** [playAnotherWay/Avalon#533]
Description:
I have been told by multiple people that this talent gives you 6% spell hit as well. I want to know for sure if it does give spell hit here because getting 17% spell hit  would be much easier if it does.

How it should work:
It SHOULD only modify the chance to hit with weapon skills and auto attacks and not affect spells as well.
External sources:
https://www.mmo-champion.com/threads/622605-Dual-wield-specialization?p=5844903&viewfull=1#post5844903
Who are you?
Lumsham

**Comment by seadix** [comment]
No it does not give you spell hit, and it wont show in the hit status same with heroic presence tho as enhance shaman you need 14% spell hit to soft cap in pve -1% since youre drainei 13%

**Comment by Azraelft** [comment]
Yeah, I assume it doesn't work for spell hit. I just had  multiple people telling me it did so I wanted 100% confirmation from devs that it does not just incase it was bugged here to give spell hit.
