### ISSUE TITLE
Quest: Gluttonous Lurkers unable to gather quest items

### ISSUE THREAD

**Issue by Psykopyro** [playAnotherWay/Avalon#56]
Description: The quest requires you to throw Zul'Drak rats at the lurkers, at which point they are supposed to go friendly. You can them click on them to harvest their crystals. Throwing the rats just aggro's them, and killing them does not give crystals either.

How to reproduce bug: accept quest, gather nearby rat and throw it at a lurker

How it should work: Once rat has been thrown at a lurker, lurker should become clickable to harvest a quest item.

Screenshots: N/A

Relevant AddOns used: N/A

External sources: N/A

Who are you? PsykoPyheal

**Comment by MarceloTheOne** [comment]
Can't reproduce, remember that you have to throw rat 5 times at one lurker to gather quest item.
