### ISSUE TITLE
**Attack through the wall/tree

### ISSUE THREAD

**Issue by rkgodx** [playAnotherWay/Avalon#85]
Hello. I would like to tell you about a bugg in STV zone and maybe will be the same in other zones too. A hunter attack me through the tree, then I run to walls and there again I wasn't hide because he attack me through the walls too :D Maybe in nagrand arena will be the same, check this and please fix it if you can. Thanks you and happy holidays.

**Comment by MarceloTheOne** [comment]
https://github.com/playAnotherWay/Avalon/issues/53
