### ISSUE TITLE
The addon Autoquest DC'ing you

### ISSUE THREAD

**Issue by Raydevv** [playAnotherWay/Avalon#87]
Description:
The addon Autoquest DC's you from the game if you've got a full inventory, whereas it shouldn't but just say that your inventory is full.

How to reproduce bug:
Try to turn in a quest with a reward whilst your bags is fulled with Autoquest

How it should work:
Shouldn't crash you, just say your inventory is full & stay on the turn-in screen

Screenshots:
-

Relevant AddOns used:
Autoquest

External sources:
-

Who are you?
Raydev

**Comment by Noodlerogue88** [comment]
Spam protection of the server kicking you
